Repository mezzio/mezzio, pull requests merged in 2020-04, with the labels that each got.

#30 Fixes syntax for code examples in list
  docs/book/v3/features/router/aura.md
  docs/book/v3/features/router/uri-generation.md
  docs/book/v3/features/template/twig.md
Labels: Bug, Documentation

#34 Update suggested version of laminas-auradi-config dependency
  CHANGELOG.md
  composer.json
Labels: Enhancement

#33 Update debug-toolbars.md
  docs/book/v3/cookbook/debug-toolbars.md
Labels: Documentation, Enhancement
