Repository mezzio/mezzio, pull requests merged in 2021-04, with the labels that each got.

#66 Switch from Travis to GitHub actions
  .github/workflows/continuous-integration.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  composer.lock
Labels: Enhancement

#65 Add example nginx conf
  docs/book/v3/cookbook/using-a-base-path.md
Labels: Documentation, Enhancement

#67 Fix documentation linting errors
  docs/book/cookbook/autowiring-routes-and-pipelines.md
  docs/book/cookbook/common-prefix-for-routes.md
  docs/book/cookbook/custom-404-page-handling.md
  docs/book/cookbook/debug-toolbars.md
  docs/book/cookbook/flash-messengers.md
  docs/book/cookbook/modular-layout.md
  docs/book/cookbook/passing-data-between-middleware.md
  docs/book/cookbook/route-specific-pipeline.md
  docs/book/cookbook/setting-locale-depending-routing-parameter.md
  docs/book/cookbook/setting-locale-without-routing-parameter.md
  docs/book/cookbook/using-a-base-path.md
  docs/book/cookbook/using-custom-view-helpers.md
  docs/book/cookbook/using-laminas-form-view-helpers.md
  docs/book/cookbook/using-routed-middleware-class-as-controller.md
  docs/book/features/application.md
  docs/book/features/container/aura-di.md
  docs/book/features/container/delegator-factories.md
  docs/book/features/container/factories.md
  docs/book/features/container/intro.md
  docs/book/features/container/laminas-servicemanager.md
  docs/book/features/container/pimple.md
  docs/book/features/emitters.md
  docs/book/features/error-handling.md
  docs/book/features/helpers/body-parse.md
  docs/book/features/helpers/content-length.md
  docs/book/features/helpers/intro.md
  docs/book/features/helpers/server-url-helper.md
  docs/book/features/helpers/url-helper.md
  docs/book/features/middleware-types.md
  docs/book/features/middleware/implicit-methods-middleware.md
  docs/book/features/modular-applications.md
  docs/book/features/router/aura.md
  docs/book/features/router/fast-route.md
  docs/book/features/router/interface.md
  docs/book/features/router/intro.md
  docs/book/features/router/laminas-router.md
  docs/book/features/router/piping.md
  docs/book/features/router/uri-generation.md
  docs/book/features/template/interface.md
  docs/book/features/template/intro.md
  docs/book/features/template/laminas-view.md
  docs/book/features/template/middleware.md
  docs/book/features/template/plates.md
  docs/book/features/template/twig.md
  docs/book/getting-started/features.md
  docs/book/getting-started/skeleton.md
  docs/book/getting-started/standalone.md
  docs/book/index.md
  docs/book/reference/cli-tooling.md
  docs/book/reference/mezzio-projects.md
  docs/book/reference/migration/rc-to-v1.md
  docs/book/reference/migration/to-v1-1.md
  docs/book/reference/migration/to-v2.md
  docs/book/reference/usage-examples.md
  docs/book/v1/index.md
  docs/book/v2/index.md
  docs/book/v3/index.md
  docs/book/why-mezzio.md
Labels: Documentation

#51 Psalm integration
  composer.json
  composer.lock
  phpstan.neon
  psalm-baseline.xml
  psalm.xml.dist
  src/Container/ApplicationConfigInjectionDelegator.php
  src/Container/ErrorResponseGeneratorFactory.php
  src/Container/NotFoundHandlerFactory.php
  src/Container/ServerRequestErrorResponseGeneratorFactory.php
  src/Container/WhoopsFactory.php
  src/Middleware/WhoopsErrorResponseGenerator.php
  src/MiddlewareFactory.php
  test/Container/ApplicationConfigInjectionDelegatorTest.php
  test/Container/ErrorHandlerFactoryTest.php
  test/Container/RequestHandlerRunnerFactoryTest.php
  test/Container/ServerRequestErrorResponseGeneratorFactoryTest.php
  test/Container/WhoopsFactoryTest.php
  test/Container/WhoopsPageHandlerFactoryTest.php
  test/Handler/NotFoundHandlerTest.php
  test/Middleware/LazyLoadingMiddlewareTest.php
  test/MiddlewareFactoryTest.php
  test/Response/ServerRequestErrorResponseGeneratorTest.php
  test/Router/IntegrationTest.php
Labels: Enhancement
