Repository mezzio/mezzio, pull requests merged in 2023-05, with the labels that each got.

#155 Migrate phpunit configuration
  composer.json
  composer.lock
  phpunit.xml.dist
Labels: Enhancement

#157 Update lockfile
  composer.lock
Labels: Bug

#151 Provide `MiddlewareFactoryInterface`
  src/Application.php
  src/ConfigProvider.php
  src/Container/ApplicationConfigInjectionDelegator.php
  src/Container/ApplicationFactory.php
  src/Container/MiddlewareFactoryFactory.php
  src/MiddlewareFactory.php
  src/MiddlewareFactoryInterface.php
  test/ApplicationTest.php
  test/ConfigProviderTest.php
  test/Container/ApplicationConfigInjectionDelegatorTest.php
  test/Container/ApplicationFactoryTest.php
  test/MiddlewareFactoryTest.php
Labels: Enhancement

#152 Made lazy loaded middleware inspectable
  src/Middleware/LazyLoadingMiddleware.php
Labels: Enhancement

#159 Restore `LazyLoadingMiddleware::$middlewareName`
  src/Middleware/LazyLoadingMiddleware.php
Labels: BC Break, Bug, Enhancement
