Repository mezzio/mezzio, pull requests merged in 2024-10, with the labels that each got.

#195 Minor docs linting fixes
  docs/book/v1/cookbook/setting-locale-depending-routing-parameter.md
  docs/book/v1/cookbook/setting-locale-without-routing-parameter.md
  docs/book/v1/cookbook/using-routed-middleware-class-as-controller.md
  docs/book/v1/features/application.md
  docs/book/v1/features/container/intro.md
  docs/book/v1/features/template/interface.md
  docs/book/v1/reference/usage-examples.md
  docs/book/v2/cookbook/setting-locale-depending-routing-parameter.md
  docs/book/v2/cookbook/setting-locale-without-routing-parameter.md
  docs/book/v2/cookbook/using-routed-middleware-class-as-controller.md
  docs/book/v2/features/application.md
  docs/book/v2/features/container/intro.md
  docs/book/v2/features/error-handling.md
  docs/book/v2/features/helpers/content-length.md
  docs/book/v2/features/middleware/implicit-methods-middleware.md
  docs/book/v2/features/template/interface.md
  docs/book/v2/getting-started/standalone.md
  docs/book/v2/reference/migration.md
  docs/book/v2/reference/usage-examples.md
  docs/book/v3/cookbook/double-pass-middleware.md
  docs/book/v3/cookbook/setting-locale-depending-routing-parameter.md
  docs/book/v3/cookbook/setting-locale-without-routing-parameter.md
  docs/book/v3/features/container/intro.md
  docs/book/v3/features/container/middleware-factory.md
  docs/book/v3/features/error-handling.md
  docs/book/v3/features/helpers/body-params.md
  docs/book/v3/features/helpers/content-length.md
  docs/book/v3/features/helpers/template-variable-container.md
  docs/book/v3/features/router/piping.md
  docs/book/v3/features/router/uri-generation.md
  docs/book/v3/features/template/interface.md
  docs/book/v3/reference/migration.md
Labels: Bug, Documentation

#193 Improve the Features section of the documentation
  docs/book/v4/getting-started/features.md
Labels: Documentation

#196 Improve the Features section of the documentation
  docs/book/v3/getting-started/features.md
Labels: Documentation, Enhancement

#194 Add support for PHP 8.4
  .laminas-ci.json
  composer.json
  composer.lock
  phpunit.xml.dist
Labels: Enhancement

#198 Fixes tooling commands namespaces in the quick start
  docs/book/v3/getting-started/quick-start.md
Labels: Bug, Documentation

#181 Minor update to the Error Handling docs
  docs/book/v3/features/error-handling.md
Labels: Documentation

#199 Merge release 3.20.1 into 3.21.x
  docs/book/v3/features/error-handling.md
  docs/book/v3/getting-started/quick-start.md
Labels: Documentation

#200 Merge release 3.20.1 into 4.0.x
  docs/book/v3/features/error-handling.md
  docs/book/v3/getting-started/quick-start.md
Labels: Documentation
